# Generated by Django 3.2.25 on 2024-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0004_auto_20240602_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdata',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='signupdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='signupdata',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
